/*
 *  Copyright IBM Corp. 2026
 *
 *  This source code is licensed under the Apache-2.0 license found in the
 *  LICENSE file in the root directory of this source tree.
 *
 *  @license
 */

import "@carbon/ai-chat/dist/es/web-components/cds-aichat-custom-element/index.js";

import {
  BusEventType,
  CarbonTheme,
  type ChatInstance,
  type MessageResponse,
  type PublicConfig,
  type UserDefinedItem,
} from "@carbon/ai-chat";
import { html, LitElement, css } from "lit";
import { customElement, state, property } from "lit/decorators.js";

import { customSendMessage } from "./customSendMessage";
import { customLoadHistory } from "./customLoadHistory";

interface UserDefinedSlotsMap {
  [key: string]: UserDefinedSlot;
}

interface UserDefinedSlot {
  message: UserDefinedItem;
  fullMessage: MessageResponse;
}

const config: PublicConfig = {
  history: {
    isOn: true,
  },
  messaging: {
    customSendMessage,
    customLoadHistory,
  },
  layout: {
    showFrame: false,
    customProperties: {
      "messages-max-width": `max(60vw, 672px)`,
    },
  },
  openChatByDefault: true,
  injectCarbonTheme: CarbonTheme.WHITE,
};

@customElement("my-app")
export class Demo extends LitElement {
  static styles = css`
    .chat-custom-element {
      height: 100vh;
      width: 100vw;
    }
  `;

  @state()
  accessor instance!: ChatInstance;

  @state()
  accessor userDefinedSlotsMap: UserDefinedSlotsMap = {};

  @state()
  accessor activeResponseId: string | null = null;

  @state()
  accessor valueFromParent: string = Date.now().toString();

  onBeforeRender = (instance: ChatInstance) => {
    // Set the instance in state.
    this.instance = instance;
    const initialState = instance.getState();
    this.activeResponseId = initialState.activeResponseId ?? null;

    // Register user defined response handler.
    instance.on({
      type: BusEventType.USER_DEFINED_RESPONSE,
      handler: this.userDefinedHandler,
    });

    instance.on({
      type: BusEventType.STATE_CHANGE,
      handler: (event: any) => {
        if (
          event.previousState?.activeResponseId !==
          event.newState?.activeResponseId
        ) {
          this.activeResponseId = event.newState.activeResponseId ?? null;
        }
      },
    });
  };

  /**
   * Each user defined event is tied to a slot deeply rendered with-in AI chat that is generated at runtime.
   * Here we make sure we store all these slots along with their relevant data in order to be able to dynamically
   * render the content to be slotted when this.renderUserDefinedSlots() is called in the render function.
   */
  userDefinedHandler = (event: any) => {
    const { data } = event;
    this.userDefinedSlotsMap[data.slot] = {
      message: data.message,
      fullMessage: data.fullMessage,
    };
    this.requestUpdate();
  };

  /**
   * This renders each of the dynamically generated slots that were generated by the AI chat by calling
   * this.renderUserDefinedResponse on each one.
   */
  renderUserDefinedSlots() {
    const userDefinedSlotsKeyArray = Object.keys(this.userDefinedSlotsMap);
    return userDefinedSlotsKeyArray.map((slot) => {
      return this.renderUserDefinedResponse(slot);
    });
  }

  /**
   * Here we process a single item from this.userDefinedSlotsMap. We go ahead and use a switch statement to decide
   * which element we should be rendering.
   */
  renderUserDefinedResponse(slot: keyof UserDefinedSlotsMap) {
    const slotData = this.userDefinedSlotsMap[slot];
    if (!slotData) {
      return null;
    }

    const { message, fullMessage } = slotData;

    const userDefinedMessage = message;
    const isLatest =
      Boolean(this.activeResponseId) &&
      fullMessage?.id === this.activeResponseId;

    // Check the "type" we have used as our key.
    switch (userDefinedMessage.user_defined?.user_defined_type) {
      case "my_unique_identifier":
        // And here is an example using your own component.
        return html`<div slot=${slot}>
          <div class="external">
            ${userDefinedMessage.user_defined.text as string}
            <div>
              Latest response id:
              ${this.activeResponseId ? this.activeResponseId : "none yet"}
            </div>
            <div>
              Is this the most recent message? ${isLatest ? "Yes" : "Nope"}
            </div>
          </div>
        </div>`;
      default:
        return null;
    }
  }

  /**
   * You only need to provide slots for the writable elements you want to use. In this demo, we fill them all with big
   * green boxes.
   *
   * Workspace panel element is now using the workspace-writeable-element-example component. and we render it with custom example for demo purpose. but remember its a custom writeable element.
   */
  renderWriteableElementSlots() {
    const ALWAYS_RENDER_KEYS = ["workspacePanelElement", "historyPanelElement"];
    const elements = this.instance?.writeableElements ?? {};

    const keys = Object.keys(elements);

    const finalKeys = [
      ...ALWAYS_RENDER_KEYS,
      ...keys.filter((k) => !ALWAYS_RENDER_KEYS.includes(k)),
    ];

    return finalKeys.map(
      (key) => html`
        <div slot=${key}>
          ${key === "workspacePanelElement"
            ? html`
                <workspace-writeable-element-example
                  location=${key}
                  .instance=${this.instance}
                  .valueFromParent=${this.valueFromParent}
                ></workspace-writeable-element-example>
              `
            : key === "historyPanelElement"
              ? html`
                  <history-writeable-element-example
                    location=${key}
                    .instance=${this.instance}
                    .valueFromParent=${this.valueFromParent}
                    .isMobile=${false}
                  ></history-writeable-element-example>
                `
              : html`
                  <writeable-element-example
                    location=${key}
                    valueFromParent=${this.valueFromParent}
                  ></writeable-element-example>
                `}
        </div>
      `,
    );
  }

  render() {
    return html`
      <cds-aichat-custom-element
         class="chat-custom-element"
        .history=${config.history}
        .injectCarbonTheme=${config.injectCarbonTheme ?? undefined}
        .layout=${config.layout}
        .openChatByDefault=${config.openChatByDefault}
        .messaging=${config.messaging}
        .onBeforeRender=${this.onBeforeRender}
        >${this.renderUserDefinedSlots()}${this.renderWriteableElementSlots()}</cds-aichat-custom-element
      >
    `;
  }
}
