name: Accessibility issue ♿
description: Report an accessibility or usability issue
title: '[A11y]: '
type: 'bug'
body:
  - type: markdown
    attributes:
      value: '## Welcome!'
  - type: markdown
    attributes:
      value:
        Thanks for taking the time to fill out this accessibility report. IBM
        firmly believes that web and software experiences should be accessible
        for everyone. Carbon is committed to following and complying with
        accessibility best practices.
  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: Which browser(s) are you experiencing the issue?
      multiple: true
      options:
        - Chrome
        - Safari
        - Firefox
        - Edge
  - type: dropdown
    id: os
    attributes:
      label: Operating system
      description: Which operating system are you using?
      multiple: true
      options:
        - Windows
        - MacOS
        - Other
  - type: input
    id: version
    attributes:
      label: Package version
      description: 'Which version of Carbon AI Chat are you using?'
      placeholder: e.g. v0.1.0
    validations:
      required: true
  - type: input
    id: react-version
    attributes:
      label: React version (if applicable)
      description: 'Which React version are you using?'
      placeholder: e.g. v17.0.2
  - type: input
    id: tool
    attributes:
      label: Automated testing tool and ruleset
      description: 'Which tool and ruleset uncovered the issue?'
      placeholder:
        e.g. IBM Equal Access Accessibility Checker - Latest Deployment
    validations:
      required: true
  - type: input
    id: technology
    attributes:
      label: Assistive technology
      description: 'Did you experience the issue using an assistive technology?'
      placeholder: e.g. JAWS, MacOS VoiceOver
  - type: textarea
    id: description
    attributes:
      label: Description
      description:
        "Tell us more about the accessibility issue that you're experiencing"
      placeholder: What did you expect to happen? What happened instead?
    validations:
      required: true
  - type: input
    id: wcag
    attributes:
      label: WCAG 2.1 violation
      description: 'Does this violate a specific WCAG 2.1 checkpoint?'
      placeholder: e.g Success Criterion 1.4.3 Contrast (Minimum)
  - type: input
    id: example-url
    attributes:
      label: Reproduction / example
      description: |
        Re-create the issue using [CodeSandbox](https://codesandbox.io/) or [Stackblitz](https://stackblitz.com).
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description:
        'How do we reproduce the accessibility violation you described using the
        reproduction/example link above?'
    validations:
      required: true
  - type: dropdown
    id: severity
    attributes:
      label: Suggested severity
      description:
        'Read more to understand our [severity
        levels](https://github.com/carbon-design-system/carbon/blob/main/docs/guides/support.md#severity)'
      options:
        - 'Severity 1 = Must be fixed ASAP. The response must be swift. Someone
          from the team must drop all current work and be immediately reassigned
          to address the issue.'
        - 'Severity 2 = User cannot complete task, and/or no workaround within
          the user experience of a given component.'
        - 'Severity 3 = User can complete task, and/or has a workaround within
          the user experience of a given component.'
        - 'Severity 4 = Unrelated to a user task, has a workaround or does not
          need a workaround.'
  - type: checkboxes
    id: terms
    attributes:
      label: Code of conduct
      description: Please confirm the following
      options:
        - label:
            I agree to follow this project's [Code of
            Conduct](https://github.com/carbon-design-system/carbon/blob/main/.github/CODE_OF_CONDUCT.md)
          required: true
        - label:
            I checked the [current
            issues](https://github.com/carbon-design-system/carbon-ai-chat/issues) for
            duplicate problems
