name: Feature request or enhancement 💡
description: Suggest an idea for this project
title: '[Feature Request]: '
type: 'enhancement'
body:
  - type: markdown
    attributes:
      value: '## Welcome!'
  - type: markdown
    attributes:
      value:
        Use this template if you want to request a new feature, or a change to
        an existing feature. If you are reporting a bug or problem, please use
        the bug template instead.
  - type: textarea
    id: problem
    attributes:
      label: The problem
      description:
        'Provide a clear and concise description of what the problem this new
        feature is trying to solve. (For example, I find it frustrating
        when...). Be sure to attach screenshots or videos to illustrate the
        problem.'
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: The solution
      description:
        'Provide a clear and concise description of what you would like to
        happen instead. Be sure to attach screenshots or videos to illustrate
        the solution if possible. Design specs are highly encouraged.'
  - type: textarea
    id: user-research
    attributes:
      label: Examples
      description:
        Provide sample content, references, or audits of solutions solving the
        same problem in other applications/websites.
  - type: input
    id: application
    attributes:
      label: Application / product
      description: "What application, product, or Carbon local system do you work on?"
  - type: dropdown
    id: backend
    attributes:
      label: How do you use AI Chat?
      options:
        - 'with watsonx Orchestrate'
        - 'with watsonx Assistant'
        - 'with my own backend'
  - type: dropdown
    id: blocker
    attributes:
      label: Is this a blocker to using AI Chat
      options:
        - 'No'
        - 'Yes'
  - type: dropdown
    id: priority
    attributes:
      label: Business priority
      options:
        - 'High Priority = pressing release'
        - 'Medium Priority = upcoming release but is not pressing'
        - 'Low Priority = release date is not dependent on fix or not upcoming'
  - type: input
    id: date
    attributes:
      label: If you have a specific date, when do you need this by?
      description: 'We will take this into account when release planning, but do not guarantee a date based on requests'
  - type: textarea
    id: contacts
    attributes:
      label: Additional contacts
      description: 'Provide name, email, slack'
  - type: input
    id: resources
    attributes:
      label: Available extra resources
      description: 'What resources do you have to assist this effort?'
  - type: markdown
    attributes:
      value:
        '_Carbon is a collaborative system. We encourage teams to build
        components and submit them for integration as either add-ons or core
        components. To better understand our feature request process and what
        happends after you submit this issue, [check out the
        docs](https://github.com/carbon-design-system/carbon/blob/main/docs/guides/support.md#type-enhancement-)
        on Github._'
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: Please confirm the following
      options:
        - label:
            I agree to follow this project's [Code of
            Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
          required: true
