name: Deploy PR previews

# This action uploads the Web Component storyook deploy preview to GitHub Pages
# and posts the relevant url to the related PR. Once the PR is closed, the deploy preview
# in GitHub Pages will be automatically deleted.
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency: preview-${{ github.ref }}

jobs:
  deploy-preview:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

      - name: Use Node.js 20.x
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
        with:
          node-version: "20.x"
      - name: Install and Build
        # skip the build if the PR has been closed
        if: github.event.action != 'closed'
        run: |
          cd packages/ai-chat
          npm install
          npm run build
          npm run storybook:build

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./packages/ai-chat/storybook-static
