# Deploy canary storybook environment from `main` branch to Github Pages
name: Deploy canary storybook

# occurs on every push to the `main` branch or can be manually triggered
on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

      - name: Use Node.js 20.x
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
        with:
          node-version: "20.x"
      - name: Install dependencies
        run: npm install
      - name: Build project
        run: npm run build
      - name: Build static Web Components storybook
        run: |
          cd packages/ai-chat
          npm run storybook:build
      # Deploy to canary folder in Github Pages using `gh-pages` package
      - name: Deploy to canary
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npx gh-pages -d packages/ai-chat/storybook-static -u "github-actions-bot <support+actions@github.com>" --dest canary --message "chore(deploy): deploy to gh-pages canary"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
