# Publish the canary CDN artifacts to Cloud Object Storage
name: Publish canary CDN artifacts

# occurs on every push to the `main` branch or can be manually triggered
on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish-cdn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
        with:
          fetch-depth: "0"
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"
      - name: Install dependencies
        run: |
          npm install
          npm run build

      # Upload the CDN artifacts to the `canary` tag folder
      # ie. https://1.www.s81c.com/common/carbon/web-components/tag/v2/canary/breadcrumb.min.js
      - name: Upload to COS under the `canary` folder
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks
        env:
          AWS_S3_BUCKET: ${{ secrets.COMMON_COS_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.COMMON_COS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.COMMON_COS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.COMMON_COS_REGION }}
          AWS_S3_ENDPOINT: https://${{ secrets.COMMON_COS_ENDPOINT }}
          SOURCE_DIR: "packages/ai-chat/dist"
          DEST_DIR: "common/carbon/ai-chat/tag/canary"
